// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AlertType } from "./AlertType";

/**
 * 报警日志条目
 */
export type AlertLogEntry = {
  id: string;
  chain: string;
  contractAddress: string;
  symbol: string;
  message: string;
  timestamp: number;
  alertType: AlertType;
};
