// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 报警类型枚举
 */
export type AlertType =
  | "volume1m"
  | "volume5m"
  | "priceChange1m"
  | "priceChange5m";
