// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DataAction } from "./DataAction";
import type { HotlistItem } from "./HotlistItem";
import type { MemeScanItem } from "./MemeScanItem";

export type DataPayload =
  | { "category": "hotlist"; type: DataAction; data: Array<HotlistItem> }
  | { "category": "meme_new"; type: DataAction; data: Array<MemeScanItem> }
  | { "category": "meme_migrated"; type: DataAction; data: Array<MemeScanItem> }
  | { "category": "Unknown" };
