// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type HotlistItem = {
  chain: string;
  contractAddress: string;
  symbol: string;
  icon: string | null;
  price: number | null;
  marketCap: number | null;
  volume1h: number | null;
  volume24h: number | null;
  priceChange1h: number | null;
  priceChange24h: number | null;
  volume5m: number | null;
  priceChange5m: number | null;
  volume1m: number | null;
  priceChange1m: number | null;
  volume4h: number | null;
  priceChange4h: number | null;
  source?: string;
  narrative?: string;
};
