// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { KlineTick } from "./KlineTick";
import type { LiquidityPoint } from "./LiquidityPoint";

export type KlineHistoryResponse = {
  address: string;
  chain: string;
  interval: string;
  data: Array<KlineTick>;
  /**
   * 流动性历史（可选）
   */
  liquidityHistory: Array<LiquidityPoint> | null;
};
