// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 流动性历史数据点
 */
export type LiquidityPoint = {
  /**
   * 秒级 Unix 时间戳（分钟对齐）
   */
  time: number;
  /**
   * 流动性绝对值 (USD)
   */
  value: number;
};
